//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlast.Util.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vlast.Util.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;appSettings&gt;
        ///    &lt;add key=&quot;AWS_ACCESS_KEY_ID&quot; value=&quot;AKIAJ6DDC7DCKZ4RATYA&quot; /&gt;
        ///    &lt;add key=&quot;AWS_SECRET_KEY&quot; value=&quot;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&quot; /&gt;
        ///    &lt;add key=&quot;CONNECTION_STRING&quot; value=&quot;User Id=mypushadm;Password=C3dr0aws;Server=mypush-db.cpxpkaromimb.us-east-1.rds.amazonaws.com;Database=mypush_dev;&quot; /&gt;
        ///    &lt;add key=&quot;S3_BUCKET_NAME&quot; value=&quot;mypush-dev&quot; /&gt;
        ///    &lt;add key=&quot;SNS_APP_WP_NAME&quot; value=&quot;arn:aws:sns:us-east-1:055489339799:app/WNS/DEV-MyPush-WP&quot; /&gt;
        ///    &lt;add key=&quot;SNS_APP_IOS_NAME&quot; val [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DEV_PARAMETER {
            get {
                return ResourceManager.GetString("DEV_PARAMETER", resourceCulture);
            }
        }
    }
}
