//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlast.Broker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vlast.Broker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;APNS_SANDBOX&quot;: &quot;{ \&quot;aps\&quot; : { \&quot;alert\&quot; : { \&quot;title\&quot; : \&quot;##TITLE##\&quot;, \&quot;body\&quot; : \&quot;##MSG##\&quot; } , \&quot;badge\&quot; : 1,\&quot;content-available\&quot; :##SILENT##, \&quot;sound\&quot; :\&quot;##SOUND##\&quot;}, \&quot;extras\&quot;:\&quot;##EXTRA##\&quot;}&quot;.
        /// </summary>
        internal static string APNS_MSG {
            get {
                return ResourceManager.GetString("APNS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;GCM&quot;:&quot;{\&quot;delay_while_idle\&quot;:false,\&quot;data\&quot;:{\&quot;title\&quot;:\&quot;##TITLE##\&quot; ,\&quot;message\&quot;:\&quot;##MSG##\&quot;,  \&quot;extras\&quot;:\&quot;##EXTRA##\&quot;}}&quot;.
        /// </summary>
        internal static string GCM_MSG {
            get {
                return ResourceManager.GetString("GCM_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;WNS&quot; : &quot;&lt;toast launch=&apos;{2}&apos;&gt;&lt;visual&gt;&lt;binding template=&apos;ToastText02&apos;&gt;&lt;text id=&apos;1&apos;&gt;{0}&lt;/text&gt;&lt;text id=&apos;2&apos;&gt;{1}&lt;/text&gt;&lt;/binding&gt;&lt;/visual&gt;&lt;/toast&gt;&quot;.
        /// </summary>
        internal static string WPNS_TOAST {
            get {
                return ResourceManager.GetString("WPNS_TOAST", resourceCulture);
            }
        }
    }
}
