//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vlast.Gamific.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vlast.Gamific.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select profile.Name as SenderName,
        ///worker.LogoId as SenderLogoId,
        ///message.Id as Id,
        ///message.FirmId as FirmId,
        ///message.Sender as Sender,
        ///message.TeamId as TeamId,
        ///message.Message as Message,
        ///message.SendDateTime as SendDateTime
        ///from Firm_Message message,
        ///Account_UserProfile profile,
        ///Firm_Worker worker
        ///where message.TeamId = {1}
        ///and message.Sender = profile.Id
        ///and message.FirmId = {0}
        ///and worker.UserId = profile.Id 
        ///order by message.SendDateTime;.
        /// </summary>
        internal static string SQL_MESSAGES_BY_TEAM {
            get {
                return ResourceManager.GetString("SQL_MESSAGES_BY_TEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select team.id as IdTeam,
        ///team.logoId as LogoId,
        ///team.TeamName as TeamName,
        ///teamWorkerType.TypeName as ProfileName,
        ///sponsorProfile.Name as SponsorName,
        ///teamWorkerType.TypeName as TypeName
        ///from Firm_Team team,
        ///Firm_Worker sponsor,
        ///Account_UserProfile sponsorProfile,
        ///Firm_Worker_Type teamWorkerType
        ///where team.FirmId = {0}
        ///and sponsor.id = team.sponsorId
        ///and sponsorProfile.id = sponsor.UserId
        ///and teamWorkerType.Id = team.WorkerTypeId
        ///and team.status = 1
        ///and sponsor.status = 1
        ///limit {1}, {2};.
        /// </summary>
        internal static string SQL_TEAMS {
            get {
                return ResourceManager.GetString("SQL_TEAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///team.Id as IdTeam,
        ///team.TeamName as TeamName,
        ///user.Name as SponsorName
        ///FROM Firm_Team as team,
        ///Firm_Worker as worker,
        ///Account_UserProfile as user
        ///WHERE team.SponsorId = worker.Id
        ///AND worker.UserId = user.Id
        ///AND team.id in ({1})
        ///and worker.firmId = {0}
        ///and team.firmId = {0}
        ///and team.status = 1
        ///and worker.status = 1.
        /// </summary>
        internal static string SQL_TEAMS_DTOS_BY_TEAMS_ID {
            get {
                return ResourceManager.GetString("SQL_TEAMS_DTOS_BY_TEAMS_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select team.*
        ///from Firm_Team team,
        ///Firm_Team_Worker teamWorker
        ///where team.FirmId = {1}
        ///and teamWorker.FirmId = {1}
        ///and teamWorker.WorkerId = {0}
        ///and team.Id = teamWorker.TeamId
        ///and team.status = 1
        ///and teamWorker.status = 1;.
        /// </summary>
        internal static string SQL_TEAMS_FROM_WORKER {
            get {
                return ResourceManager.GetString("SQL_TEAMS_FROM_WORKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select worker.id as idWorker,
        ///worker.logoId as LogoId,
        ///systemProfile.Name,
        ///systemProfile.id as IdProfile,
        ///userProfile.Email,
        ///userProfile.id as idUser,
        ///userProfile.Name,
        ///userProfile.cpf,
        ///userProfile.Phone,
        ///worker.WorkerTypeId as WorkerTypeId
        ///from Firm_Worker worker, 
        ///Account_UserProfile systemProfile, 
        ///Account_UserProfile userProfile
        ///where worker.FirmId = {0}
        ///and worker.id = {1}
        ///and systemProfile.Id = worker.UserId
        ///and userProfile.Id = worker.UserId
        ///and worker.status = 1;.
        /// </summary>
        internal static string SQL_WORKER {
            get {
                return ResourceManager.GetString("SQL_WORKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select worker.id as IdWorker,
        ///worker.logoId as LogoId,
        ///workerType.TypeName as WorkerTypeName,
        ///workerType.id as WorkerTypeId,
        ///userProfile.Email,
        ///userProfile.Name,
        ///userProfile.cpf,
        ///userProfile.Phone,
        ///userProfile.Id as IdUser
        ///from Firm_Worker worker, 
        ///Firm_Worker_Type workerType, 
        ///Account_UserProfile userProfile
        ///where worker.FirmId = {0}
        ///and workerType.Id = worker.WorkerTypeId 
        ///and userProfile.Id = worker.UserId
        ///and worker.status = 1
        ///and workerType.status = 1
        ///limit {1}, {2};.
        /// </summary>
        internal static string SQL_WORKERS {
            get {
                return ResourceManager.GetString("SQL_WORKERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select worker.id as IdWorker,
        ///userProfile.Email,
        ///userProfile.Name,
        ///userProfile.cpf,
        ///userProfile.Phone,
        ///systemProfile.TypeName,
        ///systemProfile.id as IdProfile
        ///from Firm_Worker worker,
        ///Firm_Worker_Type systemProfile, 
        ///Account_UserProfile userProfile
        ///where worker.FirmId = {0}
        ///and systemProfile.ProfileName = {1}
        ///and userProfile.Id = worker.UserId
        ///and systemProfile.Id = worker.WorkerTypeId
        ///and worker.status = 1
        ///and 0 = (select count(1) from Firm_Team team1 where team1.SponsorId = worker.id)
        ///limit  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_WORKERS_BY_PROFILE {
            get {
                return ResourceManager.GetString("SQL_WORKERS_BY_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select worker.id as IdWorker,
        ///worker.logoId as LogoId,
        ///workerProfile.Email,
        ///workerProfile.Name,
        ///workerProfile.cpf,
        ///workerProfile.Phone,
        ///teamWorker.Id as IdAssociation
        ///from Firm_Worker worker,
        ///Account_UserProfile workerProfile,
        ///Firm_Team team,
        ///Firm_Team_Worker teamWorker
        ///where team.Id = {0}
        ///and worker.FirmId = {1}
        ///and workerProfile.Id = worker.UserId
        ///and teamWorker.WorkerId = worker.Id
        ///and team.Id = teamWorker.TeamId
        ///and team.status = 1
        ///and teamWorker.status = 1
        ///and worker.status = 1
        ///limit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_WORKERS_FROM_TEAM {
            get {
                return ResourceManager.GetString("SQL_WORKERS_FROM_TEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select worker.id as IdWorker,
        ///workerProfile.Email,
        ///workerProfile.Name,
        ///workerProfile.cpf,
        ///workerProfile.Phone
        ///from Firm_Worker worker,
        ///Account_UserProfile workerProfile,
        ///Firm_Team team
        ///where team.FirmId = {0}
        ///and worker.FirmId = {0}
        ///and team.Id = {1}
        ///and worker.WorkerTypeId = {2}
        ///and workerProfile.Id = worker.UserId
        ///and worker.Id != team.SponsorId
        ///and worker.id not in (select teamWorker.WorkerId 
        ///from Firm_Team as team, Firm_Team_Worker as teamWorker 
        ///where teamWorker.FirmId = {0}
        ///and teamW [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_WORKERS_TO_ASSOCIATE {
            get {
                return ResourceManager.GetString("SQL_WORKERS_TO_ASSOCIATE", resourceCulture);
            }
        }
    }
}
